### ISSUE TITLE
print_powerlog_native native missing

### ISSUE THREAD

**Issue by gabrielepmattia** [mt7-dev/cm_android_frameworks_base#1]
Error stack:

```
Failed to register native method android.util.Log.print_powerlog_native(ILjava/lang/String;Ljava/lang/String;)I in /system/framework/framework.jar
07-24 10:28:28.403 20197 20197 E art     : ----- class 'Landroid/util/Log;' cl=0x0 -----
07-24 10:28:28.403 20197 20197 E art     :   objectSize=488 (440 from super)
07-24 10:28:28.403 20197 20197 E art     :   access=0x0008.0011
07-24 10:28:28.403 20197 20197 E art     :   super='java.lang.Class<java.lang.Object>' (cl=0x0)
07-24 10:28:28.403 20197 20197 E art     :   vtable (0 entries, 11 in super):
07-24 10:28:28.403 20197 20197 E art     :   direct methods (24 entries):
07-24 10:28:28.403 20197 20197 E art     :      0: void android.util.Log.<clinit>()
07-24 10:28:28.403 20197 20197 E art     :      1: void android.util.Log.<init>()
07-24 10:28:28.403 20197 20197 E art     :      2: int android.util.Log.d(java.lang.String, java.lang.String)
07-24 10:28:28.403 20197 20197 E art     :      3: int android.util.Log.d(java.lang.String, java.lang.String, java.lang.Throwable)
07-24 10:28:28.403 20197 20197 E art     :      4: int android.util.Log.e(java.lang.String, java.lang.String)
07-24 10:28:28.403 20197 20197 E art     :      5: int android.util.Log.e(java.lang.String, java.lang.String, java.lang.Throwable)
07-24 10:28:28.403 20197 20197 E art     :      6: java.lang.String android.util.Log.getStackTraceString(java.lang.Throwable)
07-24 10:28:28.403 20197 20197 E art     :      7: int android.util.Log.i(java.lang.String, java.lang.String)
07-24 10:28:28.403 20197 20197 E art     :      8: int android.util.Log.i(java.lang.String, java.lang.String, java.lang.Throwable)
07-24 10:28:28.403 20197 20197 E art     :      9: boolean android.util.Log.isLoggable(java.lang.String, int)
07-24 10:28:28.403 20197 20197 E art     :     10: int android.util.Log.println(int, java.lang.String, java.lang.String)
07-24 10:28:28.403 20197 20197 E art     :     11: int android.util.Log.println_native(int, int, java.lang.String, java.lang.String)
07-24 10:28:28.403 20197 20197 E art     :     12: android.util.Log$TerribleFailureHandler android.util.Log.setWtfHandler(android.util.Log$TerribleFailureHandler)
07-24 10:28:28.403 20197 20197 E art     :     13: int android.util.Log.v(java.lang.String, java.lang.String)
07-24 10:28:28.403 20197 20197 E art     :     14: int android.util.Log.v(java.lang.String, java.lang.String, java.lang.Throwable)
07-24 10:28:28.403 20197 20197 E art     :     15: int android.util.Log.w(java.lang.String, java.lang.String)
07-24 10:28:28.403 20197 20197 E art     :     16: int android.util.Log.w(java.lang.String, java.lang.String, java.lang.Throwable)
07-24 10:28:28.403 20197 20197 E art     :     17: int android.util.Log.w(java.lang.String, java.lang.Throwable)
07-24 10:28:28.403 20197 20197 E art     :     18: int android.util.Log.wtf(int, java.lang.String, java.lang.String, java.lang.Throwable, boolean, boolean)
07-24 10:28:28.403 20197 20197 E art     :     19: int android.util.Log.wtf(java.lang.String, java.lang.String)
07-24 10:28:28.403 20197 20197 E art     :     20: int android.util.Log.wtf(java.lang.String, java.lang.String, java.lang.Throwable)
07-24 10:28:28.403 20197 20197 E art     :     21: int android.util.Log.wtf(java.lang.String, java.lang.Throwable)
07-24 10:28:28.403 20197 20197 E art     :     22: void android.util.Log.wtfQuiet(int, java.lang.String, java.lang.String, boolean)
07-24 10:28:28.403 20197 20197 E art     :     23: int android.util.Log.wtfStack(java.lang.String, java.lang.String)
07-24 10:28:28.403 20197 20197 E art     :   static fields (12 entries):
07-24 10:28:28.403 20197 20197 E art     :      0: int android.util.Log.ASSERT
07-24 10:28:28.403 20197 20197 E art     :      1: int android.util.Log.DEBUG
07-24 10:28:28.403 20197 20197 E art     :      2: int android.util.Log.ERROR
07-24 10:28:28.403 20197 20197 E art     :      3: int android.util.Log.INFO
07-24 10:28:28.403 20197 20197 E art     :      4: int android.util.Log.LOG_ID_CRASH
07-24 10:28:28.403 20197 20197 E art     :      5: int android.util.Log.LOG_ID_EVENTS
07-24 10:28:28.403 20197 20197 E art     :      6: int android.util.Log.LOG_ID_MAIN
07-24 10:28:28.403 20197 20197 E art     :      7: int android.util.Log.LOG_ID_RADIO
07-24 10:28:28.403 20197 20197 E art     :      8: int android.util.Log.LOG_ID_SYSTEM
07-24 10:28:28.403 20197 20197 E art     :      9: int android.util.Log.VERBOSE
07-24 10:28:28.403 20197 20197 E art     :     10: int android.util.Log.WARN
07-24 10:28:28.403 20197 20197 E art     :     11: android.util.Log$TerribleFailureHandler android.util.Log.sWtfHandler
07-24 10:28:28.403 20197 20197 F art     : art/runtime/jni_internal.cc:497] JNI FatalError called: RegisterNatives failed for 'android/util/Log'; aborting...
07-24 10:28:28.474 20197 20197 F art     : art/runtime/runtime.cc:366] Runtime aborting...
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366] Aborting thread:
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366] "main" prio=5 tid=1 Native
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   | group="" sCount=0 dsCount=0 obj=0x12c35100 self=0xb4d76500
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   | sysTid=20197 nice=0 cgrp=default sched=0/0 handle=0xb6ff5b44
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   | state=R schedstat=( 1115978240 7653360 65 ) utm=104 stm=7 core=0 HZ=100
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   | stack=0xbe293000-0xbe295000 stackSize=8MB
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   | held mutexes= "abort lock"
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #00 pc 00370e79  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_9ArtMethodEPv+160)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #01 pc 003504ef  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+150)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #02 pc 003318f3  /system/lib/libart.so (_ZNK3art10AbortState10DumpThreadERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEPNS_6ThreadE+26)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #03 pc 00331b8b  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+562)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #04 pc 000f462b  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2226)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #05 pc 00270705  /system/lib/libart.so (_ZN3art3JNI10FatalErrorEP7_JNIEnvPKc+72)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #06 pc 0000229f  /system/lib/libnativehelper.so (jniRegisterNativeMethods+98)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #07 pc 0008cf79  /system/lib/libandroid_runtime.so (_ZN7android25register_android_util_LogEP7_JNIEnv+196)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #08 pc 00061ccd  /system/lib/libandroid_runtime.so (???)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #09 pc 000621e3  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime8startRegEP7_JNIEnv+26)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #10 pc 000635df  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorINS_7String8EEEb+290)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #11 pc 00001721  /system/bin/app_process32 (???)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #12 pc 000173ad  /system/lib/libc.so (__libc_init+44)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #13 pc 00001868  /system/bin/app_process32 (???)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   (no managed stack frames)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366] Pending exception java.lang.NoSuchMethodError: no static or non-static method "Landroid/util/Log;.print_powerlog_native(ILjava/lang/String;Ljava/lang/String;)I"
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366] (Throwable with empty stack trace)Dumping all threads without appropriate locks held: thread list lock mutator lock
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366] All threads:
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366] DALVIK THREADS (4):
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366] "main" prio=5 tid=1 Runnable
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   | group="" sCount=0 dsCount=0 obj=0x12c35100 self=0xb4d76500
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   | sysTid=20197 nice=0 cgrp=default sched=0/0 handle=0xb6ff5b44
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   | state=R schedstat=( 1133535312 9807616 78 ) utm=105 stm=8 core=0 HZ=100
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   | stack=0xbe293000-0xbe295000 stackSize=8MB
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   | held mutexes= "abort lock" "mutator lock"(shared held)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #00 pc 00370e79  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_9ArtMethodEPv+160)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #01 pc 003504ef  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+150)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #02 pc 0035a3eb  /system/lib/libart.so (_ZN3art14DumpCheckpoint3RunEPNS_6ThreadE+442)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #03 pc 0035afa9  /system/lib/libart.so (_ZN3art10ThreadList13RunCheckpointEPNS_7ClosureE+212)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #04 pc 0035b4d7  /system/lib/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+142)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #05 pc 00331b01  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+424)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #06 pc 000f462b  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2226)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #07 pc 00270705  /system/lib/libart.so (_ZN3art3JNI10FatalErrorEP7_JNIEnvPKc+72)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #08 pc 0000229f  /system/lib/libnativehelper.so (jniRegisterNativeMethods+98)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #09 pc 0008cf79  /system/lib/libandroid_runtime.so (_ZN7android25register_android_util_LogEP7_JNIEnv+196)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #10 pc 00061ccd  /system/lib/libandroid_runtime.so (???)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #11 pc 000621e3  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime8startRegEP7_JNIEnv+26)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #12 pc 000635df  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorINS_7String8EEEb+290)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #13 pc 00001721  /system/bin/app_process32 (???)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #14 pc 000173ad  /system/lib/libc.so (__libc_init+44)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #15 pc 00001868  /system/bin/app_process32 (???)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   (no managed stack frames)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366] 
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366] "HeapTaskDaemon" prio=5 tid=2 Blocked
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   | group="" sCount=1 dsCount=0 obj=0x12c35280 self=0xb4d77900
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   | sysTid=20276 nice=0 cgrp=default sched=0/0 handle=0xaed6c930
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   | state=S schedstat=( 908336 9159904 14 ) utm=0 stm=0 core=0 HZ=100
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   | stack=0xaec6a000-0xaec6c000 stackSize=1038KB
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   | held mutexes=
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #00 pc 00017638  /system/lib/libc.so (syscall+28)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #01 pc 000f6b79  /system/lib/libart.so (_ZN3art17ConditionVariable4WaitEPNS_6ThreadE+96)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #02 pc 001d7425  /system/lib/libart.so (_ZN3art2gc13TaskProcessor7GetTaskEPNS_6ThreadE+104)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #03 pc 001d7937  /system/lib/libart.so (_ZN3art2gc13TaskProcessor11RunAllTasksEPNS_6ThreadE+38)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #04 pc 0000037f  /data/dalvik-cache/arm/system@framework@boot.oat (Java_dalvik_system_VMRuntime_runHeapTasks__+74)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   at dalvik.system.VMRuntime.runHeapTasks(Native method)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   - waiting to lock an unknown object
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   at java.lang.Daemons$HeapTaskDaemon.run(Daemons.java:355)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366]   at java.lang.Thread.run(Thread.java:818)
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366] 
07-24 10:28:28.475 20197 20197 F art     : art/runtime/runtime.cc:366] "FinalizerWatchdogDaemon" prio=5 tid=3 Waiting
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   | group="" sCount=1 dsCount=0 obj=0x12c35220 self=0xb4d77400
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   | sysTid=20275 nice=0 cgrp=default sched=0/0 handle=0xaee73930
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   | state=S schedstat=( 607568 6375408 3 ) utm=0 stm=0 core=0 HZ=100
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   | stack=0xaed71000-0xaed73000 stackSize=1038KB
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   | held mutexes=
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #00 pc 00017638  /system/lib/libc.so (syscall+28)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #01 pc 000f6b79  /system/lib/libart.so (_ZN3art17ConditionVariable4WaitEPNS_6ThreadE+96)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #02 pc 002becb9  /system/lib/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadExibNS_11ThreadStateE+1144)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #03 pc 002bfa17  /system/lib/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadEPNS_6mirror6ObjectExibNS_11ThreadStateE+142)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #04 pc 002d12e3  /system/lib/libart.so (_ZN3artL11Object_waitEP7_JNIEnvP8_jobject+38)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #05 pc 0000037f  /data/dalvik-cache/arm/system@framework@boot.oat (Java_java_lang_Object_wait__+74)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   at java.lang.Object.wait!(Native method)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   - waiting on <0x027300fd> (a java.lang.Daemons$FinalizerWatchdogDaemon)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   at java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:255)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   - locked <0x027300fd> (a java.lang.Daemons$FinalizerWatchdogDaemon)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:227)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   at java.lang.Thread.run(Thread.java:818)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366] 
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366] "FinalizerDaemon" prio=5 tid=4 Waiting
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   | group="" sCount=1 dsCount=0 obj=0x12c351c0 self=0xb4d76f00
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   | sysTid=20274 nice=0 cgrp=default sched=0/0 handle=0xaef7a930
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   | state=S schedstat=( 596752 9080656 4 ) utm=0 stm=0 core=0 HZ=100
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   | stack=0xaee78000-0xaee7a000 stackSize=1038KB
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   | held mutexes=
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #00 pc 00017638  /system/lib/libc.so (syscall+28)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #01 pc 000f6b79  /system/lib/libart.so (_ZN3art17ConditionVariable4WaitEPNS_6ThreadE+96)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #02 pc 002becb9  /system/lib/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadExibNS_11ThreadStateE+1144)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #03 pc 002bfa17  /system/lib/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadEPNS_6mirror6ObjectExibNS_11ThreadStateE+142)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #04 pc 002d131d  /system/lib/libart.so (_ZN3artL13Object_waitJIEP7_JNIEnvP8_jobjectxi+44)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   native: #05 pc 0000056d  /data/dalvik-cache/arm/system@framework@boot.oat (Java_java_lang_Object_wait__JI+96)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   at java.lang.Object.wait!(Native method)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   - waiting on <0x05f2b1f2> (a java.lang.ref.ReferenceQueue)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   at java.lang.Object.wait(Object.java:423)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   - locked <0x05f2b1f2> (a java.lang.ref.ReferenceQueue)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366]   at java.lang.Thread.run(Thread.java:818)
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366] 
07-24 10:28:28.476 20197 20197 F art     : art/runtime/runtime.cc:366] 
```

**Comment by gabry3795** [comment]
Fixed
